### ISSUE TITLE
Your Google Client ID is publicly visible

### ISSUE THREAD

**Issue by yousifalraheem** [HolodexNet/Musicdex#120]
## Problem

Hi, I'm not a user of Holodex but I was browsing Github for examples of how to use the Google OAuth CDN script and I found your GoogleButton example. But I noticed that you have committed your Google client ID which is a vulnerability.

https://github.com/HolodexNet/Musicdex/blob/master/src/components/login/GoogleButton.tsx#L7

## Solution

DO NOT commit secrets to Github even if the repository is private. Use `.env` files and make sure to ignore it in the `.gitignore` file. You can inject secrets during the deployment pipeline as environment variables.

Additionally, some people might already copied and used your client_id, make sure to generate a new one.

**Comment by RiceCakess** [comment]
I think Client ID is safe to expose. Thanks for the heads up though
