### ISSUE TITLE
Missing margins for Discord and Twitter connect buttons

### ISSUE THREAD

**Issue by DaniruKun** [HolodexNet/Musicdex#53]
![image](https://user-images.githubusercontent.com/5202322/163061973-02314c01-7d5b-4841-a6ab-523cb2982b9e.png)

**Comment by uetchy** [comment]
<img width="857" alt="Screen Shot 2022-04-28 at 11 24 06" src="https://user-images.githubusercontent.com/431808/165663905-006a3f9d-434f-4ced-b57c-fc03f59814b8.png">
Looks like it's already fixed🤔
