### ISSUE TITLE
☂️ Org-switch free UI + All VTubers support

### ISSUE THREAD

**Issue by uetchy** [HolodexNet/Musicdex#55]
- [ ] Org preference settings (users can choose favorite orgs)
- [ ] Render home according to user's preference orgs `/`
- [ ] Organization page to explore music beyond favorite orgs `/orgs/<org>`

## Consideration

- Performance in generating recommendations for multiple orgs
- Supporting "All Vtubers"

**Comment by sphinxrave** [comment]
Suggest the migration to take several steps:
1. build a `/favorites` page
2. switch `/` to be `/favorites` (but also need support for non-logged in users)
3. split /orgs/ pages out (this is trivial at this point)

**Comment by uetchy** [comment]
What the home `/` would look like after the migration?

**Comment by RiceCakess** [comment]
There's no layout change just a query depending on:

1. `/all` or `/org/all` will be All Vtubers
2. If user logged in `/` will load favorites/recommended
3. If user not logged in `/` will load the same as 1. `/all`
