### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by uetchy** [HolodexNet/Musicdex#60]
We could make use of [Media Session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) to achieve both keyboard shortcut and media presence capability.

> The aim is to allow users to know what's playing and to control it, without needing to open the specific page that launched it. To be able to support the Media Session API, a browser first needs a mechanism by which to access and be controlled by the OS-level media controls (such as Firefox's [MediaControl](https://bugzilla.mozilla.org/show_bug.cgi?id=1648100)).

Seems it's impossible at this moment...?

https://stackoverflow.com/questions/62300790/youtube-iframe-api-interact-with-mediasession

**Comment by RiceCakess** [comment]
Added in #69
