### ISSUE TITLE
Keyboard shortcuts suggestion

### ISSUE THREAD

**Issue by P-man2976** [HolodexNet/Musicdex#63]
I'm implementing these shortcuts:
|Key|Action|
|----|----|
|`Space`|Play / Pause / Start playing playlist (when no song is playing)|
|`Left` / `Right`|Scroll Page (Search result etc)|
|`Up` / `Down`|Change Volume (Every 5%)|
|`Ctrl/⌘`+`Left` / `Ctrl/⌘`+`Right`|Rewind / Forward track|
|`f`|Open full-screen player of Musicdex|
|`Esc`|Close full-screen player|
|`q`|Add to Queue|
|`p`|Show "Add to playlist" dialog|

Does anyone have other idea?

**Comment by RiceCakess** [comment]
https://support.spotify.com/us/article/keyboard-shortcuts/

Just follow these lol

**Comment by P-man2976** [comment]
Oh lol
I’ll follow them, thanks!
